version: '3.7'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flare
        container_name: flare-app
        restart: unless-stopped
        working_dir: /var/www/
        networks:
            - flare
        ports:
            - 80:80
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: flare-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: flare
            MYSQL_ROOT_PASSWORD: flare
            MYSQL_PASSWORD: flare
            MYSQL_USER: flare
        networks:
            - flare
        volumes:
            - flare-mysql:/var/lib/mysql

    dbadmin:
        image: phpmyadmin:latest
        container_name: flare-dbadmin
        restart: unless-stopped
        networks:
            - flare
        environment:
            PMA_HOST: db
        ports:
            - 8080:80
        depends_on:
            - db

networks:
    flare:
        driver: bridge

volumes:
    flare-mysql:
