name: Bug Report
description: File a bug report
labels: [bug]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! 
              If your issue is a design issue or otherwise requires screenshots, please post them as a reply once the issue is created.
    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: Please describe the bug in great detail. Ensure you are clear and concise.
      validations:
          required: true
    - type: textarea
      id: repro-steps
      attributes:
          label: Steps to Reproduce
          description: How can we reproduce this bug?
          value: |
              1. ...
              2. ...
              3. ...
      validations:
          required: true
    - type: input
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: What did you expect to happen?
      validations:
          required: true
    - type: input
      id: version
      attributes:
          label: Flare Version
          description: This can be found in Site Settings under Updater. If you are not on the latest version, please update then check if the bug is still present.
      validations:
          required: true
    - type: textarea
      id: notes
      attributes:
          label: Additional Information
          description: Anything else you think we should know?
