<?php

define('FLARE_MYSQL_HOST', 'DB_HOST');
define('FLARE_MYSQL_USERNAME', 'DB_USER');
define('FLARE_MYSQL_PASSWORD', 'DB_PASS');
define('FLARE_MYSQL_DB', 'DB_NAME');
define('FLARE_MYSQL_PORT', 'DB_PORT');
define('FLARE_VA_NAME', 'VA_NAME');
define('FLARE_VA_IDENTIFIER', 'VA_IDENTIFIER');
define('FLARE_VANET_API_KEY', 'VANET_API_KEY');
define('FLARE_SITE_COLOUR_MAIN_HEX', '#FF7E00');
